APS.WebApp/Controllers/ConfirmarDepoimentoController.cs
using Microsoft.AspNetCore.Mvc;

namespace APS.WebApp.Controllers
{
    public class ConfirmarDepoimentoController : Controller
    {
        public IActionResult ConfirmarDepoimento()
        {
            return View();
        }
    }
}

APS.WebApp/Controllers/DepoimentosController.cs
using APS.Dados.EntityFramework;
using APS.Dominio.Entities;
using Microsoft.AspNetCore.Mvc;

namespace APS.WebApp.Controllers
{
    public class DepoimentosController : Controller
    {
        private Contexto db = new Contexto();

        public IActionResult Index()
        {
            var resultado = db.Depoimentos
                .ToList();

            return View(resultado);
        }


        public IActionResult Inserir()
        {
            var ent = new Depoimentos();
            return View(ent);
        }

        [HttpPost]
        public IActionResult InserirConfirmar(Depoimentos ent)
        {
            db.Depoimentos.Add(ent);
            db.SaveChanges();
            return RedirectToAction("ConfirmarDepoimento");
        }



        public IActionResult ConfirmarDepoimento()
        {
            return View("ConfirmarDepoimento");
        }

    }
}

APS.WebApp/Views/Depoimentos/ConfirmarDepoimento.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">



    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.7.0/dist/css/bootstrap.min.css" integrity="..." crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.7.0/dist/js/bootstrap.bundle.min.js" integrity="..."></script>



</head>



<style>
    * {
        padding: 0;
        margin: 0;
        font-family: 'Inter', sans-serif;
    }

    header {
        background-color: #FFCCCC;
        box-shadow: 0px 3px 10px #FFCCCC;
    }

    .nav-bar {
        display: flex;
        justify-content: space-between;
        padding: 1.5rem 6rem;
    }



    .logo {
        display: block;
        width: 100px; /* Ajuste o tamanho da imagem conforme necessário */
        height: 50px; /* Ajuste o tamanho da imagem conforme necessário */
        background-image: url('../css/dstLOGO-removebg-preview.png'); /* Caminho relativo para a imagem na pasta de CSS */
        background-size: cover;
        background-repeat: no-repeat;
    }


    /*  .nav-list {
                                        display: flex;
                                        align-items: center;
                                    } */

    .nav-list ul {
        display: flex;
        justify-content: center;
        list-style: none;
    }

    .nav-item {
        margin: 0 15px;
    }

    .nav-link {
        text-decoration: none;
        font-size: 1.15rem;
        color: #808080;
        font-weight: 400;
    }

    .login-button button {
        border: none;
        padding: 9px 12px;
        border-radius: 5px;
        background-color: #E60084;
    }

        .login-button button a {
            text-decoration: none;
            color: white;
            font-weight: 200;
            font-size: 1.1rem;
        }

    .mobile-menu-icon {
        display: none;
    }

    .mobile-menu {
        display: none;
    }

    .screen and (max-width: 730px) {
        nav-bar

    {
        padding: 1.5rem 4rem;
    }



    .nav-item {
        display: none;
    }

    .login-button {
        display: none;
    }

    .mobile-menu-icon {
        display: block;
    }

        .mobile-menu-icon button {
            background-color: transparent;
            border: none;
            cursor: pointer;
        }

    .mobile-menu ul {
        display: flex;
        flex-direction: column;
        text-align: center;
        padding-bottom: 1rem;
    }

    .mobile-menu .nav-item {
        display: block;
        padding-top: 1.2rem;
    }

    .mobile-menu .login-button {
        display: block;
        padding: 1rem 2rem;
    }

        .mobile-menu .login-button button {
            width: 100%;
        }

    .open {
        display: block;
    }

    }

    * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
        font-family: Helvetica, sans-serif;
        color: #323232;
        border: none;
    }

    input, label {
        display: block;
        outline: none;
        width: 100%;
    }

    a {
        color: #E60084;
    }

    body {
        padding-top: 5vh;
        background-image: url('../img/bg-register-page.jpg');
        background-size: cover;
        background-position-y: -150px;
    }

    /* form */
    #main-container {
        width: 500px;
        margin-left: auto;
        margin-right: auto;
        background-color: #FFF;
        border-radius: 10px;
        padding: 25px;
    }

        #main-container h1 {
            text-align: center;
            margin-bottom: 25px;
            font-size: 1.6rem;
        }

    form {
        display: flex;
        flex-wrap: wrap;
        justify-content: space-between;
    }

    .full-box {
        flex: 1 1 100%;
        position: relative;
    }

    .half-box {
        flex: 1 1 45%;
        position: relative;
    }

    .spacing {
        margin-right: 2.5%;
    }

    label {
        font-weight: bold;
        font-size: .8rem;
    }

    input {
        border-bottom: 2px solid #323232;
        padding: 10px;
        font-size: .9rem;
        margin-bottom: 40px;
    }

        input:focus {
            border-color: #E60084;
        }

        input[type="submit"] {
            background-color: #E60084;
            color: #FFF;
            border: none;
            border-radius: 20px;
            height: 40px;
            cursor: pointer;
        }

    #agreement {
        margin-right: 5px;
    }

    #agreement, #agreement-label {
        display: inline-block;
        width: auto;
    }

    .error-validation {
        color: #ff1a1a;
        position: absolute;
        top: 57px;
        font-size: 12px;
    }

    .template {
        display: none;
    }


    body {
        padding-top: 0;
        background-image: url('../img/bg-register-page.jpg');
        background-size: cover;
        background-position-y: -150px;
        background-color: #FFCCCC; /* Cor de fundo vermelho claro */
    }

    .custom-navbar {
        background-color: #FFCCCC; /* Cor de fundo vermelho claro */
    }

    h5 {
        font-size: 50px; /* Tamanho da fonte desejado, ajuste conforme necessário */
        font-weight: bold;
        color: black;
    }


    .text-container {
        width: 300px;
        margin: 0 auto;
        text-align: center;
        font-size: 24px;
        padding: 20px;
    }

    .titulo {
        font-size: 24px; /* Tamanho da letra média */
        font-weight: bold; /* Negrito */
    }

    .texto {
        font-weight: bold; /* Negrito */
    }

    .hidden {
        opacity: 0;
        transition: opacity 1s;
    }


    .grid-container {
        display: grid;
        grid-template-columns: repeat(3, 1fr);
        gap: 20px;
        padding: 20px;
    }

    .grid-item {
        background-color: #ff94a6;
        border: 1px solid #ccc;
        padding: 20px;
        text-align: center;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        border-radius: 5px;
    }

    /* h2 {
                                font-size: 1.5rem;
                                color: #333;
                                margin-bottom: 10px;
                            } */

    p {
        font-size: 1rem;
        color: #666;
    }

    body {
        margin: 0;
        padding: 0;
        /* overflow: hidden; */
    }

    .grid-container {
        display: flex;
        justify-content: space-between;
        /* position: fixed; */
        top: 0;
        left: 0;
        width: 100%;
        z-index: 1;
    }

    .grid-item {
        flex: 0 0 29%; /* Ajuste a largura das colunas conforme necessário */
        padding: 20px;
        background-color: #ff94a6;
        margin: 5px;
        transition: transform 0.3s ease-in-out;
    }

        /* Adicione um efeito de transição suave para as colunas quando rolamos a página */
        .grid-item:hover {
            transform: scale(1.1);
        }





    .estilo-bonito {
        font-family: Arial, sans-serif;
        font-weight: bold;
        text-shadow: 2px 2px 5px #333;
        font-size: 50px;
        text-align: center;
    }

    .video-container {
        width: 800px; /* Largura do vídeo, ajuste conforme necessário */
        height: 450px; /* Altura do vídeo, ajuste conforme necessário */
        border: 3px solid #FF69B4; /* Cor da borda rosa */
        margin: 0 auto;
    }


    footer {
        color: #fff;
        padding: 10px 0;
        text-align: center;
        bottom: 0;
        width: 100%;
    }


    p {
        margin: 5px 0;
        color: #000; /* Cor preta */
        font-weight: bold; /* Texto em negrito */
    }

    h2 {
        font-family: Arial, sans-serif;
        font-weight: bold;
        text-shadow: 2px 2px 5px #333;
    }

/*
    .confirmation {
        background-color: #fff;
        max-width: 300px;
        margin: 100px auto;
        padding: 20px;
        border-radius: 5px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
    }

        .confirmation h1 {
            color: #333;
        }

        .confirmation .icon {
            animation: scale 1s infinite;
        }

    . scale {
        0%

    {
        transform: scale(1);
    }

    50% {
        transform: scale(1.1);
    }

    100% {
        transform: scale(1);
    }

    }*/
    .confirmation .image-container {
        text-align: center;




        transition: opacity 0.5s, transform 0.5s;

    }



    .success-message {
        background-color: #4CAF50;
        color: #fff;
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        opacity: 0;
        transform: translateY(100%);
        transition: opacity 0.5s, transform 0.5s;
    }
</style>


<body>
    <header>
        <nav class="nav-bar">
            <div class="logo">
            </div>
            <div class="nav-list">
                <ul>
                    <li class="nav-item"><a href="https://localhost:7179" class="nav-link">Início</a></li>
                    <li class="nav-item"><a href="https://localhost:7179/Sobre/Sobre" class="nav-link">Sobre</a></li>
                    <li class="nav-item"><a href="https://localhost:7179/cADASTRoPessoas" class="nav-link">Pessoas</a></li>
                    <li class="nav-item"><a href="https://localhost:7179/Missao/Missao" class="nav-link">Missão</a></li>
                    <li class="nav-item"><a href="https://localhost:7179/Depoimentos/Index" class="nav-link">Depoimentos</a></li>
                </ul>
            </div>
           
            <div class="mobile-menu-icon">
                <button onclick="menuShow()"><img class="icon" src="assets/img/menu_white_36dp.svg" alt=""></button>
            </div>
        </nav>
        <div class="mobile-menu">
            <ul>
                <li class="nav-item"><a href="#" class="nav-link">Início</a></li>
                <li class="nav-item"><a href="#" class="nav-link">Projetos</a></li>
                <li class="nav-item"><a href="#" class="nav-link">Sobre</a></li>
            </ul>
            <div class="login-button">
                <button><a href="#">Entrar</a></button>
            </div>
        </div>
    </header>

    <div class="confirmation">
        <div class="image-container">
            <img src="~/css/Confirmado-removebg-preview.png" alt="Cadastro Confirmado" style="width: 250px;">
        </div>
    </div>

    <div class="container">
        <div class="success-message">
            <center> <h1>Depoimento Efetuado com Sucesso!</h1></center>
            <center><p>Obrigado por ajudar nossa comunidade!</p></center>
             <center><p>Atenciosamente;</p></center>
             <center><p>DST'Security!</p></center>
        </div>
    </div>


    <footer>
        <div class="container">
            <p>&copy; 2023 DST'Security. Todos os direitos reservados.</p>
            <p>Data atual: <span id="currentDate"></span></p>
            <p><a href="termos-de-uso.html">Termos de Uso</a> | <a href="politica-de-privacidade.html">Política de Privacidade</a></p>
        </div>
    </footer>




</body>
<script>
    document.addEventListener("DOMContentLoaded", function () {
        const currentDate = new Date();
        const dateElement = document.getElementById("currentDate");
        dateElement.textContent = currentDate.toLocaleDateString();
    });

</script>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        const successMessage = document.querySelector(".success-message");

        setTimeout(function () {
            successMessage.style.opacity = "1";
            successMessage.style.transform = "translateY(0)";
        }, 1000);
    });


</script>


</html>

APS.WebApp/Views/Depoimentos/Index.cshtml
@using APS.Dominio.Entities;

@model IEnumerable<Depoimentos>


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="~/css/estilos.css">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">



    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.7.0/dist/css/bootstrap.min.css" integrity="..." crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.7.0/dist/js/bootstrap.bundle.min.js" integrity="..."></script>



</head>



<style>
    * {
        padding: 0;
        margin: 0;
        font-family: 'Inter', sans-serif;
    }

    /* .nav-bar, .mobile-menu {
                            width: 100%;
                        }

                        body, .container-fluid {
                            margin: 0;
                            padding: 0;
                        } */

    header {
        background-color: #FFCCCC;
        box-shadow: 0px 3px 10px #FFCCCC;
    }

    .nav-bar {
        display: flex;
        justify-content: space-between;
        padding: 1.5rem 6rem;
    }

    /*  .navbar {
                            margin: 0;
                            padding: 0;
                        } */



    /* .logo {
                            display: flex;
                            align-items: center;
                        } */



    .logo {
        display: block;
        width: 100px; /* Ajuste o tamanho da imagem conforme necessário */
        height: 50px; /* Ajuste o tamanho da imagem conforme necessário */
        background-image: url('../css/dstLOGO-removebg-preview.png'); /* Caminho relativo para a imagem na pasta de CSS */
        background-size: cover;
        background-repeat: no-repeat;
    }


    /*  .nav-list {
                            display: flex;
                            align-items: center;
                        } */

    .nav-list ul {
        display: flex;
        justify-content: center;
        list-style: none;
    }

    .nav-item {
        margin: 0 15px;
    }

    .nav-link {
        text-decoration: none;
        font-size: 1.15rem;
        color: #808080;
        font-weight: 400;
    }

    .login-button button {
        border: none;
        padding: 12px 15px;
        border-radius: 5px;
        background-color: #E60084;
    }

        .login-button button a {
            text-decoration: none;
            color: white;
            font-weight: 500;
            font-size: 1.1rem;
        }

    .mobile-menu-icon {
        display: none;
    }

    .mobile-menu {
        display: none;
    }

    .screen and (max-width: 730px) {
        nav-bar

    {
        padding: 1.5rem 4rem;
    }



    .nav-item {
        display: none;
    }

    .login-button {
        display: none;
    }

    .mobile-menu-icon {
        display: block;
    }

        .mobile-menu-icon button {
            background-color: transparent;
            border: none;
            cursor: pointer;
        }

    .mobile-menu ul {
        display: flex;
        flex-direction: column;
        text-align: center;
        padding-bottom: 1rem;
    }

    .mobile-menu .nav-item {
        display: block;
        padding-top: 1.2rem;
    }

    .mobile-menu .login-button {
        display: block;
        padding: 1rem 2rem;
    }

        .mobile-menu .login-button button {
            width: 100%;
        }

    .open {
        display: block;
    }

    }

    * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
        font-family: Helvetica, sans-serif;
        color: #323232;
        border: none;
    }

    input, label {
        display: block;
        outline: none;
        width: 100%;
    }

    a {
        color: #E60084;
    }

    body {
        padding-top: 5vh;
        background-image: url('../img/bg-register-page.jpg');
        background-size: cover;
        background-position-y: -150px;
    }

    /* form */
    #main-container {
        width: 500px;
        margin-left: auto;
        margin-right: auto;
        background-color: #FFF;
        border-radius: 10px;
        padding: 25px;
    }

        #main-container h1 {
            text-align: center;
            margin-bottom: 25px;
            font-size: 1.6rem;
        }

    form {
        display: flex;
        flex-wrap: wrap;
        justify-content: space-between;
    }

    .full-box {
        flex: 1 1 100%;
        position: relative;
    }

    .half-box {
        flex: 1 1 45%;
        position: relative;
    }

    .spacing {
        margin-right: 2.5%;
    }

    label {
        font-weight: bold;
        font-size: .8rem;
    }

    input {
        border-bottom: 2px solid #323232;
        padding: 10px;
        font-size: .9rem;
        margin-bottom: 40px;
    }

        input:focus {
            border-color: #E60084;
        }

        input[type="submit"] {
            background-color: #E60084;
            color: #FFF;
            border: none;
            border-radius: 20px;
            height: 40px;
            cursor: pointer;
        }

    #agreement {
        margin-right: 5px;
    }

    #agreement, #agreement-label {
        display: inline-block;
        width: auto;
    }

    .error-validation {
        color: #ff1a1a;
        position: absolute;
        top: 57px;
        font-size: 12px;
    }

    .template {
        display: none;
    }


    body {
        padding-top: 0;
        background-image: url('../img/bg-register-page.jpg');
        background-size: cover;
        background-position-y: -150px;
        background-color: #FFCCCC; /* Cor de fundo vermelho claro */
    }

    .custom-navbar {
        background-color: #FFCCCC; /* Cor de fundo vermelho claro */
    }

    h5 {
        font-size: 50px; /* Tamanho da fonte desejado, ajuste conforme necessário */
        font-weight: bold;
        color: black;
    }


    .text-container {
        width: 300px;
        margin: 0 auto;
        text-align: center;
        font-size: 24px;
        padding: 20px;
    }

    .titulo {
        font-size: 24px; /* Tamanho da letra média */
        font-weight: bold; /* Negrito */
    }

    .texto {
        font-weight: bold; /* Negrito */
    }

    .hidden {
        opacity: 0;
        transition: opacity 1s;
    }


    .grid-container {
        display: grid;
        grid-template-columns: repeat(3, 1fr);
        gap: 20px;
        padding: 20px;
    }

    .grid-item {
        background-color: #ff94a6;
        border: 1px solid #ccc;
        padding: 20px;
        text-align: center;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        border-radius: 5px;
    }

    /* h2 {
                    font-size: 1.5rem;
                    color: #333;
                    margin-bottom: 10px;
                } */

    p {
        font-size: 1rem;
        color: #666;
    }

    body {
        margin: 0;
        padding: 0;
        /* overflow: hidden; */
    }

    .grid-container {
        display: flex;
        justify-content: space-between;
        /* position: fixed; */
        top: 0;
        left: 0;
        width: 100%;
        z-index: 1;
    }

    .grid-item {
        flex: 0 0 29%; /* Ajuste a largura das colunas conforme necessário */
        padding: 20px;
        background-color: #ff94a6;
        margin: 5px;
        transition: transform 0.3s ease-in-out;
    }

        /* Adicione um efeito de transição suave para as colunas quando rolamos a página */
        .grid-item:hover {
            transform: scale(1.1);
        }





    .estilo-bonito {
        font-family: Arial, sans-serif;
        font-weight: bold;
        text-shadow: 2px 2px 5px #333;
        font-size: 50px;
        text-align: center;
    }

    .video-container {
        width: 800px; /* Largura do vídeo, ajuste conforme necessário */
        height: 450px; /* Altura do vídeo, ajuste conforme necessário */
        border: 3px solid #FF69B4; /* Cor da borda rosa */
        margin: 0 auto;
    }


    footer {
        color: #fff;
        padding: 10px 0;
        text-align: center;
        bottom: 0;
        width: 100%;
    }


    p {
        margin: 5px 0;
        color: #000; /* Cor preta */
        font-weight: bold; /* Texto em negrito */
    }

    h2 {
        font-family: Arial, sans-serif;
        font-weight: bold;
        text-shadow: 2px 2px 5px #333;
    }



    .table-striped {
        background-color: #FF69B4;
    }

    .table-sm th {
        font-size: 14px;
    }

    .table-sm td {
        font-size: 12px;
    }

    table.table.table-striped.table-sm {
        background-color: pink;
    }

    .tabela-rosa {
        background-color: pink;
    }


    .whatsapp-icon {
        position: fixed;
        bottom: 20px;
        right: 20px;
        font-size: 8px; /* Ajuste o tamanho do ícone conforme necessário */
        color: green;
        z-index: 1000;
        cursor: pointer;
    }

        /* Se você estiver usando uma imagem em vez do ícone do Font Awesome */
        .whatsapp-icon img {
            width: 50px; /* Ajuste a largura da imagem conforme necessário */
            height: 50px; /* Ajuste a altura da imagem conforme necessário */
        }

    .whatsapp-link {
        text-decoration: none; /* Remove o sublinhado padrão do link */
        color: inherit; /* Mantém a cor padrão do texto */
        /* Adicione estilos adicionais conforme necessário */
    }

</style>


<body>
    <header>
        <nav class="nav-bar">
            <div class="logo">
            </div>
            <div class="nav-list">
                <ul>
                    <li class="nav-item"><a href="https://localhost:7179" class="nav-link">Início</a></li>
                    <li class="nav-item"><a href="https://localhost:7179/Sobre/Sobre" class="nav-link">Sobre</a></li>
                    <li class="nav-item"><a href="https://localhost:7179/cADASTRoPessoas" class="nav-link">Pessoas</a></li>
                    <li class="nav-item"><a href="https://localhost:7179/CadastroPessoas/Missao" class="nav-link">Missão</a></li>
                    <li class="nav-item"><a href="https://localhost:7179/Depoimentos/Index" class="nav-link">Relatos</a></li>
                   
                </ul>
            </div>
            <div class="login-button">
                <button><a href="https://localhost:7179/cADASTRoPessoas/Inserir">Cadastre</a></button>
            </div>
            <div class="login-button">
                <button><a href="https://localhost:7179/Autenticacao/Index">Entrar</a></button>
            </div>
            <div class="mobile-menu-icon">
                <button onclick="menuShow()"><img class="icon" src="assets/img/menu_white_36dp.svg" alt=""></button>
            </div>
        </nav>
        <div class="mobile-menu">
            <ul>
                <li class="nav-item"><a href="#" class="nav-link">Início</a></li>
                <li class="nav-item"><a href="#" class="nav-link">Projetos</a></li>
                <li class="nav-item"><a href="#" class="nav-link">Sobre</a></li>
            </ul>
            <div class="login-button">
                <button><a href="#">Entrar</a></button>
            </div>
        </div>
    </header>


    


    <h2 class=" animated">
        Unidos, podemos construir uma comunidade que celebra a diversidade,
        acolhe a compaixão e promove a saúde sexual responsável.
        Sua participação no Programa de Apoio às DSTs não é apenas solidariedade, 
        mas um investimento em um futuro acessível a todos. Ao se inscrever, você
        se torna um elo precioso na corrente de transformação. Junte-se a nós. Juntos, 
        fortalecemos nossos laços.
    </h2>
    <center>
        <h2>Com apreço, João Pedro e Guilherme</h2>
    </center>
    <center>
    <h2>
            DST'Security
        </h2>
    </center>



    

    <h5 class="animated-heading">CONFIRA OS DEPOIMENTOS DAS PESSOAS QUE AJUDAMOS</h5>


    <table class="table table-striped table-sm tabela-rosa">
        <thead>
            <tr class="text-center">
                
                <th class="text-center">Nome</th>
                
                <th class="text-center">Relato</th>
             
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td class="blink text-center">@item.Nome1</td>
                    <td class="blink text-center">@item.Relato</td> 
                    
                        
                   
                </tr>
            }
        </tbody>
    </table>

    <a href="https://wa.me/5534992277918" target="_blank" class="whatsapp-link">
        <div class="whatsapp-icon">
            <img src="~/css/b357a82495676c6c808a7b8c818f5460-removebg-preview.png" alt="WhatsApp Icon">
        </div>
    </a>
    <footer>
        <div class="container">
            <p>&copy; 2023 DST'Security. Todos os direitos reservados.</p>
            <p>Data atual: <span id="currentDate"></span></p>
            <p><a href="termos-de-uso.html">Termos de Uso</a> | <a href="politica-de-privacidade.html">Política de Privacidade</a></p>
        </div>
    </footer>


    <script>

        document.addEventListener("DOMContentLoaded", function () {
            const currentDate = new Date();
            const dateElement = document.getElementById("currentDate");
            dateElement.textContent = currentDate.toLocaleDateString();
        });





    </script>
    </body>
    </html>

APS.WebApp/Views/Depoimentos/Inserir.cshtml
@using APS.Dominio.Entities;
@model Depoimentos


<div id="main-container">
    <h1>Escreva seu Relato</h1>
    <form asp-action="InserirConfirmar" asp-controller="Depoimentos" method="POST">

        <div class="full-box">
            <center><label for="Nome">Nome(se não quiser se identificar, escreva ANONIMO)</label></center>
            <input asp-for="Nome1" class="form-control" />
        </div>
        <div class="full-box">
            <center><label for="Relato">Relato</label></center>
            <textarea asp-for="Relato" class="form-control" rows="8"></textarea>
        </div>


        
        <hr />
        <div class="full-box">
            <input id="btn-submit" type="submit" value="Registrar">
        </div>
    </form>
</div>

<p class="error-validation template"> </p>