APS.WebApp/Controllers/CadastroMedicosController.cs
using APS.Dados.EntityFramework;
using Microsoft.AspNetCore.Mvc;
using APS.Dominio.Entities;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace APS.WebApp.Controllers
{
    public class CadastroMedicosController : Controller
    {
        private Contexto db = new Contexto();

        public IActionResult Index()
        {
            var resultado = db.CadastroMedicos
                .ToList();

            return View(resultado);
        }


        public IActionResult Inserir()
        {
            var ent = new CadastroMedicos();

            ViewBag.SexosDisponiveis = new List<SelectListItem> {
                new SelectListItem { Value = "M", Text = "Masculino" },
                new SelectListItem { Value = "F", Text = "Feminino" },
                new SelectListItem { Value = "O", Text = "Outro" },
            };

            return View(ent);
        }

        [HttpPost]
        public IActionResult InserirConfirmar(CadastroMedicos ent)
        {
            db.CadastroMedicos.Add(ent);
            db.SaveChanges();
            return RedirectToAction("ConfirmarCadastro");
        }



        public IActionResult ConfirmarCadastro()
        {
            return View("ConfirmarCadastro");
        }
    }
}

APS.WebApp/Views/CadastroMedicos/ConfirmarCadastro.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">



    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.7.0/dist/css/bootstrap.min.css" integrity="..." crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.7.0/dist/js/bootstrap.bundle.min.js" integrity="..."></script>



</head>



<style>
    * {
        padding: 0;
        margin: 0;
        font-family: 'Inter', sans-serif;
    }

    header {
        background-color: #FFCCCC;
        box-shadow: 0px 3px 10px #FFCCCC;
    }

    .nav-bar {
        display: flex;
        justify-content: space-between;
        padding: 1.5rem 6rem;
    }



    .logo {
        display: block;
        width: 100px; /* Ajuste o tamanho da imagem conforme necessário */
        height: 50px; /* Ajuste o tamanho da imagem conforme necessário */
        background-image: url('../css/dstLOGO-removebg-preview.png'); /* Caminho relativo para a imagem na pasta de CSS */
        background-size: cover;
        background-repeat: no-repeat;
    }


    /*  .nav-list {
                                            display: flex;
                                            align-items: center;
                                        } */

    .nav-list ul {
        display: flex;
        justify-content: center;
        list-style: none;
    }

    .nav-item {
        margin: 0 15px;
    }

    .nav-link {
        text-decoration: none;
        font-size: 1.15rem;
        color: #808080;
        font-weight: 400;
    }

    .login-button button {
        border: none;
        padding: 9px 12px;
        border-radius: 5px;
        background-color: #E60084;
    }

        .login-button button a {
            text-decoration: none;
            color: white;
            font-weight: 200;
            font-size: 1.1rem;
        }

    .mobile-menu-icon {
        display: none;
    }

    .mobile-menu {
        display: none;
    }

    .screen and (max-width: 730px) {
        nav-bar

    {
        padding: 1.5rem 4rem;
    }



    .nav-item {
        display: none;
    }

    .login-button {
        display: none;
    }

    .mobile-menu-icon {
        display: block;
    }

        .mobile-menu-icon button {
            background-color: transparent;
            border: none;
            cursor: pointer;
        }

    .mobile-menu ul {
        display: flex;
        flex-direction: column;
        text-align: center;
        padding-bottom: 1rem;
    }

    .mobile-menu .nav-item {
        display: block;
        padding-top: 1.2rem;
    }

    .mobile-menu .login-button {
        display: block;
        padding: 1rem 2rem;
    }

        .mobile-menu .login-button button {
            width: 100%;
        }

    .open {
        display: block;
    }

    }

    * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
        font-family: Helvetica, sans-serif;
        color: #323232;
        border: none;
    }

    input, label {
        display: block;
        outline: none;
        width: 100%;
    }

    a {
        color: #E60084;
    }

    body {
        padding-top: 5vh;
        background-image: url('../img/bg-register-page.jpg');
        background-size: cover;
        background-position-y: -150px;
    }

    /* form */
    #main-container {
        width: 500px;
        margin-left: auto;
        margin-right: auto;
        background-color: #FFF;
        border-radius: 10px;
        padding: 25px;
    }

        #main-container h1 {
            text-align: center;
            margin-bottom: 25px;
            font-size: 1.6rem;
        }

    form {
        display: flex;
        flex-wrap: wrap;
        justify-content: space-between;
    }

    .full-box {
        flex: 1 1 100%;
        position: relative;
    }

    .half-box {
        flex: 1 1 45%;
        position: relative;
    }

    .spacing {
        margin-right: 2.5%;
    }

    label {
        font-weight: bold;
        font-size: .8rem;
    }

    input {
        border-bottom: 2px solid #323232;
        padding: 10px;
        font-size: .9rem;
        margin-bottom: 40px;
    }

        input:focus {
            border-color: #E60084;
        }

        input[type="submit"] {
            background-color: #E60084;
            color: #FFF;
            border: none;
            border-radius: 20px;
            height: 40px;
            cursor: pointer;
        }

    #agreement {
        margin-right: 5px;
    }

    #agreement, #agreement-label {
        display: inline-block;
        width: auto;
    }

    .error-validation {
        color: #ff1a1a;
        position: absolute;
        top: 57px;
        font-size: 12px;
    }

    .template {
        display: none;
    }


    body {
        padding-top: 0;
        background-image: url('../img/bg-register-page.jpg');
        background-size: cover;
        background-position-y: -150px;
        background-color: #FFCCCC; /* Cor de fundo vermelho claro */
    }

    .custom-navbar {
        background-color: #FFCCCC; /* Cor de fundo vermelho claro */
    }

    h5 {
        font-size: 50px; /* Tamanho da fonte desejado, ajuste conforme necessário */
        font-weight: bold;
        color: black;
    }


    .text-container {
        width: 300px;
        margin: 0 auto;
        text-align: center;
        font-size: 24px;
        padding: 20px;
    }

    .titulo {
        font-size: 24px; /* Tamanho da letra média */
        font-weight: bold; /* Negrito */
    }

    .texto {
        font-weight: bold; /* Negrito */
    }

    .hidden {
        opacity: 0;
        transition: opacity 1s;
    }


    .grid-container {
        display: grid;
        grid-template-columns: repeat(3, 1fr);
        gap: 20px;
        padding: 20px;
    }

    .grid-item {
        background-color: #ff94a6;
        border: 1px solid #ccc;
        padding: 20px;
        text-align: center;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        border-radius: 5px;
    }

    /* h2 {
                                    font-size: 1.5rem;
                                    color: #333;
                                    margin-bottom: 10px;
                                } */

    p {
        font-size: 1rem;
        color: #666;
    }

    body {
        margin: 0;
        padding: 0;
        /* overflow: hidden; */
    }

    .grid-container {
        display: flex;
        justify-content: space-between;
        /* position: fixed; */
        top: 0;
        left: 0;
        width: 100%;
        z-index: 1;
    }

    .grid-item {
        flex: 0 0 29%; /* Ajuste a largura das colunas conforme necessário */
        padding: 20px;
        background-color: #ff94a6;
        margin: 5px;
        transition: transform 0.3s ease-in-out;
    }

        /* Adicione um efeito de transição suave para as colunas quando rolamos a página */
        .grid-item:hover {
            transform: scale(1.1);
        }





    .estilo-bonito {
        font-family: Arial, sans-serif;
        font-weight: bold;
        text-shadow: 2px 2px 5px #333;
        font-size: 50px;
        text-align: center;
    }

    .video-container {
        width: 800px; /* Largura do vídeo, ajuste conforme necessário */
        height: 450px; /* Altura do vídeo, ajuste conforme necessário */
        border: 3px solid #FF69B4; /* Cor da borda rosa */
        margin: 0 auto;
    }


    footer {
        color: #fff;
        padding: 10px 0;
        text-align: center;
        bottom: 0;
        width: 100%;
    }


    p {
        margin: 5px 0;
        color: #000; /* Cor preta */
        font-weight: bold; /* Texto em negrito */
    }

    h2 {
        font-family: Arial, sans-serif;
        font-weight: bold;
        text-shadow: 2px 2px 5px #333;
    }

    /*
        .confirmation {
            background-color: #fff;
            max-width: 300px;
            margin: 100px auto;
            padding: 20px;
            border-radius: 5px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
        }

            .confirmation h1 {
                color: #333;
            }

            .confirmation .icon {
                animation: scale 1s infinite;
            }

        . scale {
            0%

        {
            transform: scale(1);
        }

        50% {
            transform: scale(1.1);
        }

        100% {
            transform: scale(1);
        }

        }*/
    .confirmation .image-container {
        text-align: center;
        transition: opacity 0.5s, transform 0.5s;
    }



    .success-message {
        background-color: #4CAF50;
        color: #fff;
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        opacity: 0;
        transform: translateY(100%);
        transition: opacity 0.5s, transform 0.5s;
    }
</style>


<body>
    <header>
        <nav class="nav-bar">
            <div class="logo">
            </div>
            <div class="nav-list">
                <ul>
                    <li class="nav-item"><a href="https://localhost:7179" class="nav-link">Início</a></li>
                    <li class="nav-item"><a href="https://localhost:7179/Sobre/Sobre" class="nav-link">Sobre</a></li>
                    <li class="nav-item"><a href="https://localhost:7179/cADASTRoPessoas" class="nav-link">Pessoas</a></li>
                    <li class="nav-item"><a href="https://localhost:7179/CadastroPessoas/Missao" class="nav-link">Missão</a></li>
                    <li class="nav-item"><a href="https://localhost:7179/Depoimentos/Index" class="nav-link">Relatos</a></li>
                </ul>
            </div>
           
            <div class="mobile-menu-icon">
                <button onclick="menuShow()"><img class="icon" src="assets/img/menu_white_36dp.svg" alt=""></button>
            </div>
        </nav>
        <div class="mobile-menu">
            <ul>
                <li class="nav-item"><a href="#" class="nav-link">Início</a></li>
                <li class="nav-item"><a href="#" class="nav-link">Projetos</a></li>
                <li class="nav-item"><a href="#" class="nav-link">Sobre</a></li>
            </ul>
            <div class="login-button">
                <button><a href="#">Entrar</a></button>
            </div>
        </div>
    </header>

    <div class="confirmation">
        <div class="image-container">
            <img src="~/css/Confirmado-removebg-preview.png" alt="Cadastro Confirmado" style="width: 250px;">
        </div>
    </div>

    <div class="container">
        <div class="success-message">
            <center> <h1>Cadastro Efetuado com Sucesso!</h1></center>
            <center><p>Parabéns! Seu cadastro foi realizado com sucesso.</p></center>
        </div>
    </div>


    <footer>
        <div class="container">
            <p>&copy; 2023 DST'Security. Todos os direitos reservados.</p>
            <p>Data atual: <span id="currentDate"></span></p>
            <p><a href="termos-de-uso.html">Termos de Uso</a> | <a href="politica-de-privacidade.html">Política de Privacidade</a></p>
        </div>
    </footer>




</body>
<script>
    document.addEventListener("DOMContentLoaded", function () {
        const currentDate = new Date();
        const dateElement = document.getElementById("currentDate");
        dateElement.textContent = currentDate.toLocaleDateString();
    });

</script>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        const successMessage = document.querySelector(".success-message");

        setTimeout(function () {
            successMessage.style.opacity = "1";
            successMessage.style.transform = "translateY(0)";
        }, 1000);
    });


</script>


</html>

APS.WebApp/Views/CadastroMedicos/Index.cshtml
@using APS.Dominio.Entities;

@model IEnumerable<CadastroMedicos>


<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/css/styles.css">
    <script src="~/js/script.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=SuaChaveDeAPI&libraries=places"></script>
    <title>Sua Empresa 2</title>
</head>
<body>
    <header>
        <nav class="nav-bar">
            <div class="logo">
            </div>
            <div class="nav-list">
                <ul>
                    <li class="nav-item"><a href="https://localhost:7179" class="nav-link">Início</a></li>
                    <li class="nav-item"><a href="https://localhost:7179/Sobre/Sobre" class="nav-link">Sobre</a></li>
                    <li class="nav-item"><a href="https://localhost:7179/cADASTRoPessoas" class="nav-link">Pessoas</a></li>
                    <li class="nav-item"><a href="https://localhost:7179/CadastroPessoas/Missao" class="nav-link">Missão</a></li>
                    <li class="nav-item"><a href="https://localhost:7179/Depoimentos/Index" class="nav-link">Relatos</a></li>
                </ul>
            </div>
            <div class="login-button">
                <button><a href="https://localhost:7179/PaginaInicial/PaginaInicial">Pagina Inicial</a></button>
            </div>

            <div class="mobile-menu-icon">
                <button onclick="menuShow()"><img class="icon" src="assets/img/menu_white_36dp.svg" alt=""></button>
            </div>
        </nav>

    </header>
    <header>
        <h1>Procure um Especialista</h1>
        <nav>
            <ul>
                @foreach (var item in Model)
                {
                    <li><a href="#visao">@item.Especializacao</a></li>



            



                }




            </ul>
        </nav>
    </header>

    @foreach (var item in Model)
    {




        <section id="visao" class="section">
            <center> <h2 class="estilo-bonito">@item.Especializacao</h2></center>
            <center> <h2 class="estilo-bonito">@item.Nome @item.Sobrenome</h2></center>
            <center>
                <p><strong>Local de atendimento: </strong>@item.NomeClinica </p>
                <p><strong>Endereço: </strong>@item.Endereco</p>
                <p><strong>Email: </strong>@item.Email</p>
              
                <p><strong>Telefone:</strong> @item.Numero</p>
            </center>

        </section>





    }












</body>
</html>

APS.WebApp/Views/CadastroMedicos/Inserir.cshtml
@using APS.Dominio.Entities;
@model CadastroMedicos


<div id="main-container">
    <h1><strong>Cadastre-se</strong></h1>
    <form asp-action="InserirConfirmar" asp-controller="CadastroMedicos" method="POST">

        <div class="half-box spacing">
            <label for="Nome">Nome</label>
            <input asp-for="Nome" class="form-control" placeholder="Digite seu nome" />
        </div>
        <div class="half-box">
            <label for="Sobrenome">Sobrenome</label>
            <input asp-for="Sobrenome" class="form-control" placeholder="Digite seu sobrenome" />
        </div>
        <div class="half-box spacing">
            <label for="CPF">CPF (Sem pontos e traços)</label>
            <input asp-for="CPF" class="form-control" placeholder="Digite seu CPF" />
        </div>


        <div class="half-box">
            <label for="Endereco">Endereço</label>
            <input asp-for="Endereco" class="form-control" placeholder="Digite seu endereço" />
        </div>
        <div class="full-box">
            <label for="Email">E-mail</label>
            <input asp-for="Email" class="form-control" placeholder="Digite seu e-mail" />
        </div>

        <div class="half-box spacing">
            <label for="NomeClinica">Nome da Clinica</label>
            <input asp-for="NomeClinica" class="form-control" placeholder="Digite o nome da clinica" />
        </div>
        <div class="half-box spacing">
            <label for="Especializacao">Especializacao</label>
            <input asp-for="Especializacao" class="form-control" placeholder="Digite sua especialização" />
        </div>
        <div class="half-box spacing">
            <label for="Numero">Número de Telefone</label>
            <input asp-for="Numero" class="form-control" placeholder="(__) _____-____" />
        </div>

        <div class="half-box spacing">
            @Html.LabelFor(model => model.Sexo)
            @Html.DropDownListFor(model => model.Sexo, (List<SelectListItem>)ViewBag.SexosDisponiveis, "-- Selecione --", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Sexo)
        </div>

        <div>
            <input type="checkbox" name="agreement" id="agreement">
            <label for="agreement" id="agreement-label">Eu li e aceito os <a href="#">termos de uso</a></label>
        </div>
        <hr />
        <div class="full-box">
            <input id="btn-submit" type="submit" value="Registrar">
        </div>
    </form>
</div>
<script>
    document.addEventListener("DOMContentLoaded", function () {
        var form = document.querySelector('form');

        form.addEventListener('submit', function (event) {
            var agreementCheckbox = document.getElementById('agreement');

            if (!agreementCheckbox.checked) {
                alert('Você precisa aceitar os termos de uso para continuar.');
                event.preventDefault(); // Impede o envio do formulário
            }
        });
    });
</script>
<script>
    document.addEventListener("DOMContentLoaded", function () {
        var form = document.querySelector('form');

        form.addEventListener('submit', function (event) {
            var cpfInput = document.getElementById('CPF');
            var cpfValue = cpfInput.value.replace(/\D/g, ''); // Remove caracteres não numéricos

            if (cpfValue.length !== 11 || isNaN(cpfValue)) {
                alert('CPF inválido. Por favor, insira um CPF com 11 dígitos numéricos.');
                event.preventDefault(); // Impede o envio do formulário
            }
        });
    });
</script>


<p class="error-validation template"> </p>